### ISSUE TITLE
support a default template data entry using to templating

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x-plugins/jx-secret#351]
it would be nice if we supported a defaults template entry using to templating. 

e.g. something like:

```yaml
# .jx/secret/mapping/secret-mappings.yaml
apiVersion: secret.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  defaults:
    backendType: vault
    mappingTemplate: 
      key:  "secret/data/{{ .Namespace }}/{{ .Chart }}/{{ .Secret }}/{{ . Entry }}"
```

so that folks can configure via go template expressions the default values like key/property based on template expressions
